### PR TITLE
Create a Debug installation script

### PR DESCRIPTION
**Pull request by MatejMecka**
This script should help ease debugging and returns stacktraces

### CODE REVIEW

**Comment by Rakete1111** [comment]
You should also add the same flag for C++ mode.

**Comment by MatejMecka** [comment]
Can you explain @Rakete1111 ?

**Comment by Rakete1111** [comment]
@MatejMecka The project is in C++, well most of it. And if you just put the flag for C, then it will not be set for C++, I think, not so good on CMake though, so...

**Comment by harrynull** [comment]
Try to not create a .sh file, instead, change CMakeFile and add option which allows the user to open `-ggdb3`

**Comment by MatejMecka** [comment]
@Rakete1111 the flags I left affect C++ too. It affects both the GCC compiler and G++ so I don't see a problem with that.

@harrynull If I do that i'll have to make 2 CMakeLists.txt files and Cmake only takes one.

**Comment by harrynull** [comment]
No you don't need two CMakeLists.txt
Look at how `enable_coverage` option works in CMakeLists.txt, that should help.

**Comment by saurabhshri** [comment]
Agreed with @harrynull 's comment. Feel free to open a new PR with those changes, or re-open this.

**Pull request closed without merging**
