### PR TITLE
GCI: Fix spellings and bad function names

### PR DESCRIPTION
**Pull request by ReConsolidated**
My GCI task, Gracjan Pasik

### CODE REVIEW

**Comment by saurabhshri** [comment]
Hey that looks really nice! Good job! :)

Waiting for travis build to finish before merging.

**Comment by AlexBratosin2001** [comment]
Using indefinite articles such as "a" is unwise.
e.g., "Creating **a** dictionary, this might take a little time depending (...)"
We are not creating **a** dictionary, but **the** dictionary.
Otherwise, it looks all right.

**Comment by saurabhshri** [comment]
Hello @ReConsolidated ! Could you please resolve the conflict and do the changes @alexbrt suggested so I can merge? :) Thank you!

**Comment by ReConsolidated** [comment]
I fixed that and commited

**Comment by saurabhshri** [comment]
@ReConsolidated Oops, looks like we have conflict again :) This time, as soon as you'll solve it, I'll merge it first. :)

**Comment by ReConsolidated** [comment]
@saurabhshri I updated, I hope I didn't mess anything up and everything is fine now.

**Comment by saurabhshri** [comment]
Okay, I have resolved the conflict myself. Thank you for the PR! :) Nice work.

**Pull request merged**
