### PR TITLE
Fix raw audio reading

### PR DESCRIPTION
**Pull request by harrynull**

### CODE REVIEW

**Comment by saurabhshri** [comment]
@harrynull Could you please explain the changes, and why the previous one was causing the errors.  It's always a good idea to describe PRs so that it could be easy to refer to them in future.

**Comment by harrynull** [comment]
@saurabhshri I mistakenly used ``std::istream_iterator<unsigned char>`` with ``std::vector<int16_t>``, which make the vector's size double. Then I realized ``istream_iterator<int16_t>`` didn't work either, since it was trying to parse integers from the stream. So, I turn to use ``infile.read`` to read them directly into the vector and it works.

**Comment by saurabhshri** [comment]
@harrynull So why not using `unsigned char` vector directly instead of `int16_t` and them casting it to char?

**Comment by harrynull** [comment]
@saurabhshri because _samples is a int16_t vector...

**Comment by saurabhshri** [comment]
@harrynull Haha, this is embarrassing! 😂  Alright, there's only one change I want you to do and that is change `char` to `unsigned char`. Samples aren't stored in signed bits and they lead to all kind of trouble. I had a lot of trouble last time debugging this (https://saurabhshri.github.io/2017/06/gsoc/google-summer-of-code-week-1-the-beginning) :P

**Comment by saurabhshri** [comment]
Thanks for the PR, and the good work! :)

**Pull request merged**
